-- Migration: NFS-e (Nota Fiscal de Serviço Eletrônica) e CT-e (Conhecimento de Transporte Eletrônico)
-- Padrões ABRASF (NFS-e) e schema v4.00 (CT-e)

CREATE TABLE IF NOT EXISTS nfse (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero INT NOT NULL,
    serie VARCHAR(10) DEFAULT '1',
    codigo_verificacao VARCHAR(50) COMMENT 'Código de verificação da NFS-e',
    chave_acesso VARCHAR(50) DEFAULT NULL,
    link_download_pdf VARCHAR(500) DEFAULT NULL,
    link_download_xml VARCHAR(500) DEFAULT NULL,
    tipo_documento ENUM('NFS-e', 'RPS') DEFAULT 'NFS-e',
    regime_especial_tributacao ENUM('nenhum','microempresa_municipal','estimativa','sociedade_profissionais','cooperativa','mei','mei_iss_fixo') DEFAULT 'nenhum',
    optante_simples_nacional TINYINT(1) DEFAULT 1,
    incentivo_fiscal TINYINT(1) DEFAULT 0,
    natureza_operacao VARCHAR(100) DEFAULT NULL,
    servico_id INT DEFAULT NULL,
    servico_descricao TEXT,
    servico_codigo_tributacao VARCHAR(20) DEFAULT NULL COMMENT 'Código de tributação do município',
    servico_codigo_cnae VARCHAR(10) DEFAULT NULL,
    servico_aliquota_iss DECIMAL(5,2) DEFAULT 0.00,
    servico_valor_iss DECIMAL(15,2) DEFAULT 0.00,
    servico_base_calculo DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_liquido DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_pis DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_cofins DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_inss DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_ir DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_csll DECIMAL(15,2) DEFAULT 0.00,
    servico_outras_retencoes DECIMAL(15,2) DEFAULT 0.00,
    servico_desconto_condicionado DECIMAL(15,2) DEFAULT 0.00,
    servico_desconto_incondicionado DECIMAL(15,2) DEFAULT 0.00,
    servico_valor_total DECIMAL(15,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    cliente_id INT DEFAULT NULL,
    cliente_nome VARCHAR(255) NOT NULL,
    cliente_cpf_cnpj VARCHAR(20) DEFAULT NULL,
    cliente_ie VARCHAR(20) DEFAULT NULL,
    cliente_email VARCHAR(255) DEFAULT NULL,
    cliente_endereco TEXT,
    cliente_numero VARCHAR(20) DEFAULT NULL,
    cliente_complemento VARCHAR(100) DEFAULT NULL,
    cliente_bairro VARCHAR(100) DEFAULT NULL,
    cliente_codigo_municipio VARCHAR(10) DEFAULT NULL,
    cliente_municipio VARCHAR(100) DEFAULT NULL,
    cliente_uf CHAR(2) DEFAULT NULL,
    cliente_cep VARCHAR(10) DEFAULT NULL,
    cliente_telefone VARCHAR(20) DEFAULT NULL,
    data_emissao DATE NOT NULL,
    data_competencia DATE DEFAULT NULL,
    data_vencimento DATE DEFAULT NULL,
    status ENUM('Pendente','Autorizada','Cancelada','Rejeitada','Erro','Substituida') NOT NULL DEFAULT 'Pendente',
    protocolo VARCHAR(50) DEFAULT NULL,
    justificativa_cancelamento TEXT,
    xml_file VARCHAR(255) DEFAULT NULL,
    pdf_file VARCHAR(255) DEFAULT NULL,
    rps_numero INT DEFAULT NULL,
    rps_serie VARCHAR(10) DEFAULT NULL,
    rps_tipo ENUM('RPS','RPS-Mista','RPS-Cancelamento') DEFAULT 'RPS',
    rps_substituido_id INT DEFAULT NULL,
    observacoes TEXT,
    usuario_emissao INT DEFAULT NULL,
    empresa_emitente_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (servico_id) REFERENCES produtos(id) ON DELETE SET NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfse_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nfse_id INT NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    codigo_tributacao VARCHAR(20) DEFAULT NULL,
    aliquota_iss DECIMAL(5,2) DEFAULT 0.00,
    valor_unitario DECIMAL(15,2) DEFAULT 0.00,
    quantidade DECIMAL(10,2) DEFAULT 1.00,
    valor_total DECIMAL(15,2) DEFAULT 0.00,
    desconto DECIMAL(15,2) DEFAULT 0.00,
    retido TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (nfse_id) REFERENCES nfse(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS conhecimento_transporte (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero INT NOT NULL,
    serie VARCHAR(10) DEFAULT '1',
    chave_acesso VARCHAR(44) DEFAULT NULL,
    modelo VARCHAR(3) DEFAULT '57' COMMENT 'CT-e modelo 57',
    cfop VARCHAR(10) DEFAULT NULL,
    natureza_operacao VARCHAR(100) DEFAULT NULL,
    tipo_servico ENUM('normal','subcontratacao','redespacho_intermediario','servico_municipal') DEFAULT 'normal',
    forma_pagamento ENUM('pagamento_contra entrega','pagamento_antes','pagamento_apos','outras') DEFAULT 'pagamento_contra entrega',
    modal ENUM('rodoviario','aereo','aquaviario','ferroviario','dutoviario') DEFAULT 'rodoviario',
    tipo_cte ENUM('normal','complementar','anulacao','substituto') DEFAULT 'normal',
    tomador_id INT DEFAULT NULL,
    tomador_nome VARCHAR(255) NOT NULL,
    tomador_cpf_cnpj VARCHAR(20) DEFAULT NULL,
    tomador_ie VARCHAR(20) DEFAULT NULL,
    tomador_email VARCHAR(255) DEFAULT NULL,
    tomador_endereco TEXT,
    tomador_municipio VARCHAR(100) DEFAULT NULL,
    tomador_uf CHAR(2) DEFAULT NULL,
    tomador_cep VARCHAR(10) DEFAULT NULL,
    remetente_id INT DEFAULT NULL,
    remetente_nome VARCHAR(255) DEFAULT NULL,
    remetente_cpf_cnpj VARCHAR(20) DEFAULT NULL,
    remetente_endereco TEXT,
    remetente_municipio VARCHAR(100) DEFAULT NULL,
    remetente_uf CHAR(2) DEFAULT NULL,
    destinatario_id INT DEFAULT NULL,
    destinatario_nome VARCHAR(255) DEFAULT NULL,
    destinatario_cpf_cnpj VARCHAR(20) DEFAULT NULL,
    destinatario_endereco TEXT,
    destinatario_municipio VARCHAR(100) DEFAULT NULL,
    destinatario_uf CHAR(2) DEFAULT NULL,
    expedidor_nome VARCHAR(255) DEFAULT NULL,
    recebedor_nome VARCHAR(255) DEFAULT NULL,
    valor_mercadorias DECIMAL(15,2) DEFAULT 0.00,
    valor_frete DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_recebido DECIMAL(15,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) DEFAULT 0.00,
    base_calculo_icms DECIMAL(15,2) DEFAULT 0.00,
    valor_icms DECIMAL(15,2) DEFAULT 0.00,
    aliquota_icms DECIMAL(5,2) DEFAULT 0.00,
    base_calculo_pis DECIMAL(15,2) DEFAULT 0.00,
    valor_pis DECIMAL(15,2) DEFAULT 0.00,
    base_calculo_cofins DECIMAL(15,2) DEFAULT 0.00,
    valor_cofins DECIMAL(15,2) DEFAULT 0.00,
    perc_red_base_calc_icms DECIMAL(5,2) DEFAULT 0.00,
    data_emissao DATE NOT NULL,
    data_prevista_entrega DATE DEFAULT NULL,
    status ENUM('Pendente','Autorizada','Cancelada','Rejeitada','Encerrado','Erro') NOT NULL DEFAULT 'Pendente',
    protocolo VARCHAR(50) DEFAULT NULL,
    justificativa_cancelamento TEXT,
    xml_file VARCHAR(255) DEFAULT NULL,
    dacte_file VARCHAR(255) DEFAULT NULL,
    observacoes TEXT,
    usuario_emissao INT DEFAULT NULL,
    empresa_emitente_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cte_notas_fiscais (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cte_id INT NOT NULL,
    nota_fiscal_id INT DEFAULT NULL,
    nfse_id INT DEFAULT NULL,
    chave_acesso VARCHAR(44) DEFAULT NULL,
    valor DECIMAL(15,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cte_id) REFERENCES conhecimento_transporte(id) ON DELETE CASCADE,
    FOREIGN KEY (nota_fiscal_id) REFERENCES notas_fiscais(id) ON DELETE SET NULL,
    FOREIGN KEY (nfse_id) REFERENCES nfse(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cte_componentes_valor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cte_id INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    valor DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cte_id) REFERENCES conhecimento_transporte(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
