ALTER TABLE notas_fiscais
  ADD COLUMN IF NOT EXISTS cfop VARCHAR(4) AFTER chave_acesso,
  ADD COLUMN IF NOT EXISTS natureza_operacao VARCHAR(100) AFTER cfop,
  ADD COLUMN IF NOT EXISTS finalidade ENUM('1','2','3','4') DEFAULT '1' AFTER natureza_operacao,
  ADD COLUMN IF NOT EXISTS cliente_id INT AFTER finalidade,
  ADD COLUMN IF NOT EXISTS cliente_ie VARCHAR(20) AFTER cnpj_cpf,
  ADD COLUMN IF NOT EXISTS cliente_endereco TEXT AFTER cliente_ie,
  ADD COLUMN IF NOT EXISTS cliente_municipio_ibge VARCHAR(7) AFTER cliente_endereco,
  ADD COLUMN IF NOT EXISTS cliente_uf CHAR(2) AFTER cliente_municipio_ibge,
  ADD COLUMN IF NOT EXISTS itens_json LONGTEXT AFTER cliente_uf,
  ADD COLUMN IF NOT EXISTS base_calculo_icms DECIMAL(15,2) DEFAULT 0 AFTER itens_json,
  ADD COLUMN IF NOT EXISTS valor_icms DECIMAL(15,2) DEFAULT 0 AFTER base_calculo_icms,
  ADD COLUMN IF NOT EXISTS base_calculo_pis DECIMAL(15,2) DEFAULT 0 AFTER valor_icms,
  ADD COLUMN IF NOT EXISTS valor_pis DECIMAL(15,2) DEFAULT 0 AFTER base_calculo_pis,
  ADD COLUMN IF NOT EXISTS base_calculo_cofins DECIMAL(15,2) DEFAULT 0 AFTER valor_pis,
  ADD COLUMN IF NOT EXISTS valor_cofins DECIMAL(15,2) DEFAULT 0 AFTER base_calculo_cofins,
  ADD COLUMN IF NOT EXISTS valor_iss DECIMAL(15,2) DEFAULT 0 AFTER valor_cofins,
  ADD COLUMN IF NOT EXISTS valor_irrf DECIMAL(15,2) DEFAULT 0 AFTER valor_iss,
  ADD COLUMN IF NOT EXISTS valor_inss DECIMAL(15,2) DEFAULT 0 AFTER valor_irrf,
  ADD COLUMN IF NOT EXISTS valor_csll DECIMAL(15,2) DEFAULT 0 AFTER valor_inss,
  ADD COLUMN IF NOT EXISTS retencao_pis DECIMAL(15,2) DEFAULT 0 AFTER valor_csll,
  ADD COLUMN IF NOT EXISTS retencao_cofins DECIMAL(15,2) DEFAULT 0 AFTER retencao_pis,
  ADD COLUMN IF NOT EXISTS retencao_csll DECIMAL(15,2) DEFAULT 0 AFTER retencao_cofins,
  ADD COLUMN IF NOT EXISTS retencao_iss DECIMAL(15,2) DEFAULT 0 AFTER retencao_csll,
  ADD COLUMN IF NOT EXISTS retencao_inss DECIMAL(15,2) DEFAULT 0 AFTER retencao_iss,
  ADD COLUMN IF NOT EXISTS retencao_irrf DECIMAL(15,2) DEFAULT 0 AFTER retencao_inss,
  ADD COLUMN IF NOT EXISTS protocolo VARCHAR(50) AFTER chave_acesso,
  ADD COLUMN IF NOT EXISTS xml_file VARCHAR(255) AFTER protocolo,
  ADD COLUMN IF NOT EXISTS danfe_file VARCHAR(255) AFTER xml_file,
  ADD COLUMN IF NOT EXISTS justificativa_cancelamento TEXT AFTER danfe_file,
  ADD COLUMN IF NOT EXISTS usuario_emissao INT AFTER justificativa_cancelamento,
  ADD COLUMN IF NOT EXISTS empresa_emitente_id INT AFTER usuario_emissao;
